name: kvebek
description: App for KVEBEK Boyz Assembly.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^2.2.2
  cron: ^0.2.4
  meta: ^1.2.3
  formz: ^0.3.2
  dartz: ^0.9.2
  get_it: ^5.0.3
  rxdart: ^0.25.0
  kt_dart: ^0.8.0
  pedantic: ^1.9.2
  getwidget: ^1.2.4
  equatable: ^1.2.5
  auto_route: ^0.6.9
  injectable: ^1.0.7
  workmanager: ^0.2.3
  flutter_bloc: ^6.1.1
  flutter_hooks: ^0.15.0
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  auto_animated: ^2.1.0
  json_annotation: ^3.1.1
  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.2
  flutter_blurhash: ^0.5.0
  freezed_annotation: ^0.12.0
  integration_test: ^1.0.2+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^4.1.3
  freezed: ^0.12.6
  bloc_test: ^7.1.0
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  injectable_generator: ^1.0.7
  auto_route_generator: ^0.6.10

dependency_overrides:
  lint: ^1.5.1

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
  assets:
    - assets/
    - assets/json/users.json
